---
name: Create Master Slug List on PR Merge
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Regenerate Master Slug List
        run: python3 tests/generate-slug-list.py
      - name: Commit and Push Changes to Master
        uses: EndBug/add-and-commit@v9
        with:
          author_name: NetBox-Bot
          author_email: info@netboxlabs.com
          committer_name: NetBox-Bot
          committer_email: info@netboxlabs.com
          default_author: github_actions
          message: "Regenerate master slug list after successful PR merge"
          push: true
